---
title: "SAS Toolkit for running cleaner statistical analyses: Using macros to declutter your code"
author: Luke W. Johnston
date: 2014-08-22
fontsize: 11pt
geometry: margin=1in
papersize: letterpaper
toc: TRUE
fontfamily: "DejaVu Serif"
...

